
===================================
suspect:
  CBProvider object is destroyed/freed when exiting function that created it

proof:
  class PyConnector():
      def __init__(self, mapname, vcmi_loglevel):
          logging.debug("begin")
          self.cppconn = cppconnector.CppConnector(mapname, vcmi_loglevel)
          self.cppconn.prestart()
          logging.debug("end")

  shows that CBProvider's destructor is called after "(__init__) end"

  ???but why is a COPY CONSTR called when CppConnector::start is invoked?

logs:

Loading configuration from config/test.yml
[PY][pyconnector.py] (__init__) begin
+++++++++CONSTRUCTOR (noargs)
+++++++++CONSTRUCTOR: 1|123456789012345678901234567890
------------------DESTRUCTORRRRRRR (123456789012345678901234567890)-----------
[PY][pyconnector.py] (__init__) end
[PY][pyconnector.py] (start) begin
<0x1dc759300>[CPP][cppconnector.cpp] (start) start
+++++++++COPY CONSTR: 1|123456789012345678901234567890

==============================================
suspect:
  As soon as CppConnector::start returns, things break
  That could explain why 1st call to f_getAction() works, second - not

proof:
  CppConnector::getActions to return dummy actions
  CppConnector::start to return after sleep (instead of cond.wait)

expect:
  all calls to f_getAction() will succeed UNTIL CppConnector::start returns

results:
  success
  also, attaching with debugger shows the cbprovider->f_getAction() CHANGES
  as soon as the "start" function returns

logs:

(ERR_MOVE_SELF) cannot move to self unless attacking
[0x16dd03000][ai] ERROR BAI  [0x290028018]: 3333333333333
[0x16dd03000][ai] ERROR BAI  [0x290028018]: 11111111111
[0x16dd03000][ai] INFO AAI  [0x600006c0deb8]: 44444444444
[0x16dd03000][ai] INFO AAI  [0x600006c0deb8]: NONNULL
[0x16dd03000][ai] INFO AAI  [0x600006c0deb8]: acquire Python GIL
<0x16dd03000>[CPP][cppconnector.cpp] (operator()) GIL: 1
<0x16dd03000>[CPP][cppconnector.cpp] (operator()) GETACTIONNNNNNNNNNNN
[0x16dd03000][ai] INFO AAI  [0x600006c0deb8]: 55555555555
[0x16dd03000][ai] ERROR BAI  [0x290028018]: 22222222222
[0x16dd03000][ai] ERROR BAI  [0x290028018]: Got action: 3(Move to (0, 0))
[0x16dd03000][ai] ERROR BAI  [0x290028018]: Action is INVALID: Move to (0, 0):

(ERR_MOVE_SELF) cannot move to self unless attacking
[0x16dd03000][ai] ERROR BAI  [0x290028018]: 3333333333333
[0x16dd03000][ai] ERROR BAI  [0x290028018]: 11111111111
[0x16dd03000][ai] INFO AAI  [0x600006c0deb8]: 44444444444
[0x16dd03000][ai] INFO AAI  [0x600006c0deb8]: NONNULL
<0x1dc759300>[CPP][cppconnector.cpp] (start) GIL: 0
<0x1dc759300>[CPP][cppconnector.cpp] (start) acquire Python GIL (scope-auto)
<0x1dc759300>[CPP][cppconnector.cpp] (start) GIL: 1
<0x1dc759300>[CPP][cppconnector.cpp] (start) release lock1 (return)
<0x1dc759300>[CPP][cppconnector.cpp] (start) release lock2 (return)
<0x1dc759300>[CPP][cppconnector.cpp] (start) return P_Result
[0x16dd03000][ai] INFO AAI  [0x600006c0deb8]: acquire Python GIL
[PY][pyconnector.py] (act) Return self.cppconn.act(603)
<0x1dc759300>[CPP][cppconnector.cpp] (act) GIL: 1
<0x1dc759300>[CPP][cppconnector.cpp] (act) obtain lock1
<0x1dc759300>[CPP][cppconnector.cpp] (act) obtain lock1: done
<0x1dc759300>[CPP][cppconnector.cpp] (act) set this->action = 603
<0x1dc759300>[CPP][cppconnector.cpp] (act) set state = AWAITING_RESULT
<0x1dc759300>[CPP][cppconnector.cpp] (act) cond2.notify_all()
<0x1dc759300>[CPP][cppconnector.cpp] (act) GIL: 1
<0x1dc759300>[CPP][cppconnector.cpp] (act) release Python GIL
<0x1dc759300>[CPP][cppconnector.cpp] (act) GIL: 0
<0x1dc759300>[CPP][cppconnector.cpp] (act) sleep 5s...
fish: Job 1, 'python vcmi-gym.py test' terminated by signal SIGSEGV (Address boundary error)

==============================================
suspect:
  GIL is not held when calling cbprovider->f_getAction() in AAI.cpp

proof:
  add pybind11 to MyAI, acquire GIL before the call

expected:
  second call to f_getAction() succeeds

results:
  failed (no difference)

[0x16e1f7000][ai] ERROR BAI  [0x1787e0018]: 11111111111
[0x16e1f7000][ai] INFO AAI  [0x600006cc3e98]: 44444444444
[0x16e1f7000][ai] INFO AAI  [0x600006cc3e98]: NONNULL
[0x16e1f7000][ai] INFO AAI  [0x600006cc3e98]: acquire Python GIL
<0x16e1f7000>[CPP][cppconnector.cpp] (operator()) GIL: 1
<0x16e1f7000>[CPP][cppconnector.cpp] (operator()) GETACTIONNNNNNNNNNNN
(...)
<0x16e1f7000>[CPP][cppconnector.cpp] (getAction) return Action: -2
[0x16e1f7000][ai] INFO AAI  [0x600006cc3e98]: 55555555555
[0x16e1f7000][ai] INFO AAI  [0x600006cc3e98]: 6969696969696
[0x16e1f7000][ai] INFO AAI  [0x600006cc3e98]: aaaaaaaaaaa
[0x16e1f7000][ai] INFO AAI  [0x600006cc3e98]: bbbbbbbbbb
[0x16e1f7000][ai] INFO AAI  [0x600006cc3e98]: NONNULL
fish: Job 1, 'python vcmi-gym.py test' terminated by signal SIGSEGV (Address boundary error)
